package com.examchecker.service;

public enum MathNormalizationRule {
    NULL_TO_EMPTY,
    TRIM_OUTER_WHITESPACE,
    NORMALIZE_UNICODE_DIGITS,
    REMOVE_WHITESPACE,
    NORMALIZE_PLUS,
    NORMALIZE_MINUS,
    NORMALIZE_MULTIPLICATION,
    NORMALIZE_DIVISION,
    NORMALIZE_EQUALS,
    NORMALIZE_PARENTHESES,
    NORMALIZE_DECIMAL_COMMA,
    NORMALIZE_PERCENT,
    REMOVE_QUESTION_PREFIX
}
