spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB



gemini.api-key=AIzaSyBAYbo931azMehrXj-nN-NJqKPEEiTQJ60
gemini.model=gemini-2.5-flash
gemini.base-url=https://generativelanguage.googleapis.com/v1beta